### ISSUE TITLE
Icy sample

### ISSUE THREAD

**Issue by headwinds** [fabioricali/StreamTitle#4]
I tried your library - considering this stream - "http://144.217.129.213:8702/stream?icy=http" 

It seems I can connect to it but - I see 200 request - but the promise doesn't seem to resolve - I can't read the title 

If try to hit [http://144.217.129.213:8702](http://144.217.129.213:8702) in the address bar I can see all the shoutcast info including the current show title. 

how would you go about reading it using your library?

**Comment by fabiorc428** [comment]
You can retrieve in this way
```
streamTitle({
    url: 'http://144.217.129.213:8702',
    sid: 1,
    type: 'shoutcast2'
}).then(function (title) {
    console.log(title);
}).catch(function (err) {
    console.log(err);
});
```
